vich_uploader:
    db_driver: orm
    mappings:
        happyTrip_images:
            uri_prefix: /happyTrip_images
            upload_destination: '%kernel.project_dir%/public/happyTrip_images'
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
